create table dw.fact_sales
(
  	order_id INT Not Null,
    productkey INT REFERENCES dw.products_dim(productkey),
    customerkey INT REFERENCES dw.customer_dim(customerkey),
    shiperkey INT REFERENCES dw.shipper_dim(shipperkey),
    supplierkey INT REFERENCES dw.supplier_dim(supplierkey),
    employeekey INT REFERENCES dw.employee_dim(employeekey),
    order_date_key INT REFERENCES dw.d_date(date_dim_id),
    required_date INT REFERENCES dw.d_date(date_dim_id),
    shipped_date INT REFERENCES dw.d_date(date_dim_id), 
    quantity INT,
    unit_price real,
    discount real,
    units_in_stock INT,
    units_on_order INT,
    freight real,
	actualcost real ,
	primary key(
	order_id ,
    productkey ,
    customerkey ,
	shiperkey  ,
	order_date_key  ,
	required_date	,
    shipped_date,
	supplierkey ,
	employeekey )
);

-------------------------------------------
CREATE TABLE IF NOT EXISTS dw.products_dim
(
    "product_id" INT NOT NULL ,
	"productkey" Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "product_name" character varying(40) ,
	"category_id"  INT
    );	
-------------------------------------------
CREATE TABLE dw.customer_dim (
    "CustomerID" VARCHAR(15) NOT NULL,
	"customerkey" Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CompanyName" VARCHAR(40) ,
    "ContactName" VARCHAR(30),
    "ShipCity" VARCHAR(20),
    "ShipRegion" VARCHAR(20),
	"ShipCountry" VARCHAR(20),
    "ShipAddress" VARCHAR(20)
    
);
-------------------------------------------
CREATE TABLE dw.employee_dim
(
    "EmployeeID" INT NOT NULL,
	"employeekey"  Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FirstName" VARCHAR(10) NOT NULL,
    "LastName" VARCHAR(20) NOT NULL,
    "BirthDate" DATE,
    "Title" VARCHAR(30),
    "HireDate" DATE,
    "Region" VARCHAR(15),
    "City" VARCHAR(15),
    "Country" VARCHAR(15),
    "ReportsTo" SMALLINT
 );
-------------------------------------------
CREATE TABLE dw.supplier_dim (
    supplierkey Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SupplierID INT NOT NULL,
    companyname VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255),
    contact_title VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    region VARCHAR(255),
    country VARCHAR(255)
);
-------------------------------------------
CREATE TABLE dw.shipper_dim (
    shipperkey Int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ShipperID INT Not NULL,
    CompanyName VARCHAR(100) ,
    Phone VARCHAR(20)
);



